name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:
    
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: récupérer le code  
        uses: actions/checkout@v4
      - name: installer python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: installer les dependences
        run : pip install -r requirements.txt
      - name: installer flake8
        run : pip install flake8
      - name: lancer le linter
        run : |
          flake8 app tests --count --select=E9,F63,F7,F82,F841 --show-source --statistics
          flake8 app tests --count --max-complexity=10 --max-line-length=127 --statistics
          flake8 app tests --count --max-line-length=127 --statistics
  test:
  
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run:  pip install -r requirements.txt
    - name: execute pytest
      run :  pip install pytest pytest-cov
    - name: Run tests
      run: |
        pytest tests/ -v --cov=src
  
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install build tool
      run: pip install build
    - name: Build package
      run: python -m build
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: python-package
        path: CI_PIPELINE_TP      
      