name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: récupérer le code  
        uses: action/checkout@v4
      - name: installer python
        uses: action /setup-python@v5
        with:
          python-version: "3.11"
      - name: installer les dependences
        run : pip install -r requirements.txt
      - name: lancer le linter
        run :
          flake8 app--count --select=E9,F63,F7,F82,F841 --show-source --statistics
          flake8 app--count --max-complexity=10 --max-line-length=127 --statistics
          flake8 tests --count --max-line-length=127 --statistics
      - name: lancer le tests 
        run : python -m pytest -v --cov=app